class AddEmbeddingToBooks < ActiveRecord::Migration[8.1]
  def up
    # 384-dim float32 vector produced by all-MiniLM-L6-v2.
    # 384 * 4 bytes = 1.5 KB per row. For ~7,840 books that's ~12 MB
    # total — small enough to load the whole column into memory for
    # query-time scoring.
    add_column :books, :embedding, :binary
    # Tracks which model + revision produced the stored vector so the
    # Rails app can refuse to query against embeddings generated by a
    # different model than the one loaded in data/mini_lm_onnx/.
    add_column :books, :embedding_model, :string
  end

  def down
    remove_column :books, :embedding
    remove_column :books, :embedding_model
  end
end
